# n (node), rustup
- name: Development
  become: true
  community.general.pacman:
    name: 
    - go
    - docker
    state: present

- name: Create dev dir personal
  ansible.builtin.file:
    path: /home/steven/personal
    state: directory
    mode: '0755'

- name: Create dev dir work
  ansible.builtin.file:
    path: /home/steven/work
    state: directory
    mode: '0755'

- name: n checkout
  git:
    repo: https://github.com/tj/n.git
    dest: /tmp/n
    force: true

- name: Make n
  shell: PREFIX=$HOME/.local/n make install
  args:
    chdir: /tmp/n

- name: Install node LTS
  shell: N_PREFIX=$HOME/.local/n $HOME/.local/n/bin/n lts

- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download rustup installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Neovim
  become: true
  community.general.pacman:
    name: 
    - python-pynvim
    - python-pip
    - neovim
    - tree-sitter
    - tree-sitter-cli
    - luarocks
    - wl-clipboard
    state: present
  tags:
  - setup
  - core
  - neovim

- name: Install neovim npm package
  shell: PATH="$HOME/.local/n/bin:$PATH" npm install -g neovim

- name: Install neovim lazy plugins
  shell: nvim --headless "+Lazy! sync" +qa
