- name: Install stow
  become: true
  community.general.xbps:
    name: 
    - stow
    state: present
  tags:
    - setup
    - dotfiles

- name: Make sure acl exists
  become: true
  community.general.xbps:
    name: 
    - acl
    state: present
  tags:
    - setup
    - dotfiles

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:Wolfi/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_newhostkey: yes
    version: master
    key_file: "{{ key_setup_dst }}" 
  tags:
    - setup
    - dotfiles

- name: Create greetd cache dir
  become: true
  shell: | 
    mkdir /var/cache/tuigreet
    chown _greeter:_greeter /var/cache/tuigreet
    chmod 0755 /var/cache/tuigreet
  tags:
    - setup
    - dotfiles

- name: Copy greetd config
  become: true
  copy:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/greetd/config.toml"
    dest: "/etc/greetd/config.toml"
  tags:
    - dotfiles
    - setup

- name: Stow dotfiles
  shell: ./stow.sh
  args:
    chdir: $HOME/.dotfiles
  tags:
    - setup
    - dotfiles

- name: Copy images
  shell: | 
    mkdir $HOME/Pictures/wallpaper
    cp -r $HOME/.dotfiles/images/* $HOME/Pictures/wallpaper
  tags:
    - setup
    - dotfiles
