- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "steven.wolf+git@pm.me"
  tags:
    - git

- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "Steven Wolf"
  tags:
    - git

- name: Git setup default branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
    - git

- name: Git setup rebase
  git_config:
    name: pull.rebase
    scope: global
    value: false
  tags:
    - git

- name: Git setup auto setup remote
  git_config:
    name: push.autoSetupRemote
    scope: global
    value: true
  tags:
    - git
